### ISSUE TITLE
Cannot import JSON files with comments on it

### ISSUE THREAD

**Issue by r4isen1920** [JannisX11/snowstorm#37]
For some reason, Snowstorm can't open JSON particle files that has some any form of comments inside it.

**Steps to reproduce:**
1. Create a particle, or use an example one.
2. Add comments to that JSON particle file in the form of `//` on any existing or new line.
3. Try importing it into Snowstorm.
4. For control, remove the comment and try importing it again.

At first I thought maybe there was just a delay importing it but I believe this is what's causing the issue. I hope to get this fixed! Unless otherwise if this is intended, then please change it. 

Cheers!

**Comment by SirLich** [comment]
> For some reason, Snowstorm can't open JSON particle files that has some any form of comments inside it.

Not to be contrary, [but json does not support comments.](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json).

In Minecraft we've all become a little lazy about this, since Minecraft reads and understands this odd superset of json, that seems to allow C style comments, as well as newlines in Molang. 

> Unless otherwise if this is intended, then please change it.

Even if Snowstorm could read json with comments, I can assure you it wouldn't *write* json with comments. The comments would be lost during importing.

**Comment by r4isen1920** [comment]
> Not to be contrary, but json does not support comments.

Well as far as I understand that JSON doesn't support comments, I thought this was mainly an issue: If Minecraft can understand comments in JSON, then why can't programs like this? Unless of course it is hard or tricky to implement in the first place.


> In Minecraft we've all become a little lazy about this

Become a little lazy to implement it? I mean really do appreciate talented people, by the likes of you, make great tools and utility for the community. But I just wanted to know whether or not such "ability to read JSON in a way with comments" can be coded to work with utilities like this. I'm not saying that your indolence has caused why you guys can't implement something like this, it's not and I mean that. If anything, I'm greatful to be able to use tools like this for free that other people have spent time on developing. Just wanted to know whether if it's possible or not, and why.

If comments couldnt be read in JSON, then I hope JannisX11 just added an error message in return. But there was none. So even if it couldn't be added, it's not a big deal at all – as I can manually remove the comments myself.


> I can assure you it wouldn't *write* json with comments

I mainly import particles in Snowstorm to use them as a template to create a new and different particle based on that. If I wanted to modify the existing particle by only a few bits, then I'd rather just do it manually. But the point here is that even if it can't return the original comment back, if it could at least read the comments in, then it shouldn't be a big deal.

**Comment by SirLich** [comment]
All I meant is that people learned to *expect* comments to work inside of json, when in reality hardly any system accepts it. 
It would be a bit laughable to ask for comment-support in any other industry, yet people seem to expect it in MC! I've had to add comment support into pretty much everything I've written, cause people complained otherwise. 

Its not particularly difficult to implement and plenty of libraries exist to do it. Its usually just a lot slower than loading normal json, and I don't know of a single library that would preserve comments. 

I don't know if Jannis is interested in fixing it.

**Comment by r4isen1920** [comment]
Well we're coding in this environment where what original Minecraft developers intended us to code with in the first place – it can't be helped if people expected to have this kind of thing included as well. I think it's to how people have find this relatively unique comment-support feature convenient, and has became used to it. 

Of course I'm no experienced programmer. But I know a bit of JSON and it's main use to store data. Whether it's for webhooks and whatnot, JSON is a readable format where data is stored which can be read both by computers and humans.

It's relatively simple format allowed for a variety of players to create and modify the game, into a greater extent with new scope of possibilities.

Of course JSON is not something that's mainly used for coding. It's not even close to a programming language. I think Minecraft Bedrock developers are really great developers that spent their time making things data-driven with JSON. What for? For inifinite possibilities? Who really cares why, but I think I am greatful to have them do something like this. Overall, it really makes modifying the game easier.

With that said, in *this*
